src/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('office/', include('office.urls')),
    path('auth/', include('auth_app.urls')),
    path('cbv/', include('cbv_app.urls')),
]

src/office/urls.py
from django.urls import path
from office import views


app_name = 'office'

urlpatterns = [
    path('', views.index, name='index'),
    path('addEmployee/', views.addEmployee, name='addEmployee'),
    path('employeeDetails/<int:employee_id>/', views.employeeDetails, name='employeeDetails'),
    path('editEmployee/<int:employee_id>/', views.editEmployee, name='editEmployee'),
    path('deleteEmployee/<int:employee_id>/', views.deleteEmployee, name='deleteEmployee'),
    path('addProject/<int:employee_id>/', views.addProject, name='addProject'),
    path('projectDetails/<int:project_id>/', views.projectDetails, name='projectDetails'),
    path('updateProject/<int:project_id>/', views.updateProject, name='updateProject'),
    path('deleteProject/<int:project_id>/', views.deleteProject, name='deleteProject'),
    path('testURL/', views.testURL, name='testURL'),
]

src/office/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    salary = models.IntegerField()
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name + ' - ' + self.position + ' - ' + self.department


class Project(models.Model):
    name = models.ForeignKey(Employee, on_delete=models.CASCADE)
    project_name = models.CharField(max_length=100)
    project_description = models.CharField(max_length=100)
    project_start_date = models.DateField()
    project_end_date = models.DateField()
    project_status = models.CharField(max_length=100)

    def __str__(self):
        return self.name + ' - ' + self.project_name + ' - ' + self.project_status

src/office/forms.py
from django import forms
from office.models import Employee, Project

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        labels = {
            'name': 'Name',
            'email': 'Email',
            'phone': 'Phone',
            'position': 'Position',
            'department': 'Department',
            'salary': 'Salary',
            'address': 'Address',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'position': forms.TextInput(attrs={'class': 'form-control'}),
            'department': forms.TextInput(attrs={'class': 'form-control'}),
            'salary': forms.NumberInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        labels = {
            'name': 'Name',
            'project_name': 'Project Name',
            'project_description': 'Project Description',
            'project_start_date': 'Project Start Date',
            'project_end_date': 'Project End Date',
            'project_status': 'Project Status',
        }
        widgets = {
            'name': forms.Select(attrs={'class': 'form-control'}),
            'project_name': forms.TextInput(attrs={'class': 'form-control'}),
            'project_description': forms.TextInput(attrs={'class': 'form-control'}),
            'project_start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'project_end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'project_status': forms.TextInput(attrs={'class': 'form-control'}),
        }

src/office/views.py
from unicodedata import name
from django.shortcuts import render
from office.forms import EmployeeForm, ProjectForm
from office.models import Employee, Project
from django.http import JsonResponse

# Create your views here.

# For Home Page
def index(request):
    employee_list = Employee.objects.order_by('name')
    homeDict = {'title': 'Home Page', 'employee_list': employee_list}
    return render(request, 'office/index.html', context=homeDict)


# For Add Employee Page
def addEmployee(request):
    form = EmployeeForm()

    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)

    addEmployeeDict = {'title': 'Add Employee', 'form': form}
    return render(request, 'office/addEmployee.html', context=addEmployeeDict)


# For Employee Details Page
def employeeDetails(request, employee_id):
    employee = Employee.objects.get(id=employee_id)
    project_list = Project.objects.filter(name=employee_id)
    employeeDict = {'title': 'Employee Details', 'employee': employee, 'project_list': project_list}
    return render(request, 'office/employeeDetails.html', context=employeeDict)


# For Edit Employee Page
def editEmployee(request, employee_id):
    employee = Employee.objects.get(id=employee_id)
    form = EmployeeForm(instance=employee)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save(commit=True)
            return employeeDetails(request, employee_id)

    editEmployeeDict = {'title': 'Edit Employee', 'form': form}
    return render(request, 'office/editEmployee.html', context=editEmployeeDict)


# For Delete Employee Page
def deleteEmployee(request, employee_id):
    employee = Employee.objects.get(id=employee_id)
    employee.delete()
    return index(request)


# For Add Project Page
def addProject(request, employee_id):
    employee = Employee.objects.get(id=employee_id)
    form = ProjectForm(initial={'name': employee_id})

    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return employeeDetails(request, employee_id)

    addProjectDict = {'title': 'Add Project', 'form': form, 'employee': employee}
    return render(request, 'office/addProject.html', context=addProjectDict)


# For Project Details Page
def projectDetails(request, project_id):
    project = Project.objects.get(id=project_id)
    projectDict = {'title': 'Project Details', 'project': project}
    return render(request, 'office/projectDetails.html', context=projectDict)


# For Project Update Page
def updateProject(request, project_id):
    project = Project.objects.get(id=project_id)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save(commit=True)
            return employeeDetails(request, project.name.id)

    updateProjectDict = {'title': 'Update Project', 'form': form}
    return render(request, 'office/updateProject.html', context=updateProjectDict)


# For Delete Project Page
def deleteProject(request, project_id):
    project = Project.objects.get(id=project_id)
    project.delete()
    return employeeDetails(request)



def testURL(request):
    Employee_list = Employee.objects.order_by('name')
    return JsonResponse({'Employee_list': list(Employee_list.values())})

src/templates/office/addEmployee.html
{% extends 'office/base.html' %}
{% block main_block %}

<form action="" method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>

{% endblock  %}

src/templates/office/addProject.html
{% extends 'office/base.html' %}
{% block main_block %}

<a href="{% url 'office:employeeDetails' employee_id=employee.id %}" class="btn btn-normal mb-2 p-0">Back</a>
<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ title }}</h3>
</div>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock  %}

src/templates/office/editEmployee.html
{% extends 'office/base.html' %}
{% block main_block %}

<a href="{% url 'office:index' %}" class="btn btn-normal mb-2 p-0">Back</a>
<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ title }}</h3>
</div>

<form action="" method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>

{% endblock  %}

src/templates/office/employeeDetails.html
{% extends 'office/base.html' %}
{% block main_block %}

<a href="{% url 'office:index' %}" class="btn btn-normal mb-2 p-0">Back</a>
<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ employee.name }} Details</h3>
    <a href="{% url 'office:editEmployee' employee_id=employee.id %}" class="btn btn-primary ml-auto">Edit</a>
</div>
<ul class="list-group">
    <li class="list-group-item">ID : {{ employee.id }}</li>
    <li class="list-group-item">Email : {{ employee.email }}</li>
    <li class="list-group-item">Phone : {{ employee.phone }}</li>
    <li class="list-group-item">Position : {{ employee.position }}</li>
    <li class="list-group-item">Department : {{ employee.department }}</li>
    <li class="list-group-item">Salary : {{ employee.salary }}</li>
    <li class="list-group-item">Addtess : {{ employee.address }}</li>
</ul>

<a href="{% url 'office:addProject' employee_id=employee.id %}" class="btn btn-primary my-3">Add Project</a>
{% if project_list %}
<table class="table">
    <tr>
        <th>ID</th>
        <th>Project Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    {% for project in project_list %}
    <tr>
        <td>{{ project.id }}</td>
        <td>{{ project.project_name }}</td>
        <td>{{ project.project_start_date }}</td>
        <td>{{ project.project_end_date }}</td>
        <td>{{ project.project_status }}</td>
        <td>
            <a href="{% url 'office:projectDetails' project_id=project.id %}" class="btn btn-primary">Details</a>
            <a href="{% url 'office:deleteProject' project_id=project.id %}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No projects found</p>
{% endif %}

{% endblock  %}

src/templates/office/index.html
{% extends 'office/base.html' %}

{% block main_block %}

<div class="d-flex justify-content-between mb-3">
    <h3>{{ title }}</h3>
    <a href="{% url 'office:addEmployee' %}" class="btn btn-primary">Add Employee</a>
</div>

{% if employee_list %}
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Position</th>
        <th>Department</th>
        <th>Salary</th>
        <th>Action</th>
    </tr>
    {% for employee in employee_list %}
    <tr>
        <td>{{ employee.id }}</td>
        <td>{{ employee.name }}</td>
        <td>{{ employee.email }}</td>
        <td>{{ employee.phone }}</td>
        <td>{{ employee.position }}</td>
        <td>{{ employee.department }}</td>
        <td>{{ employee.salary }}</td>
        <td>
            <a href="{% url 'office:employeeDetails' employee_id=employee.id %}" class="btn btn-primary">View</a>
            <a href="{% url 'office:editEmployee' employee_id=employee.id %}" class="btn btn-warning">Edit</a>
            <a href="{% url 'office:deleteEmployee' employee_id=employee.id %}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No employees found</p>
{% endif %}

{% endblock %}

{% block extra_js %}

{% endblock  %}

src/templates/office/projectDetails.html
{% extends 'office/base.html' %}
{% block main_block %}

{% comment %} <a href="{% url 'office:employeeDetails' employee_id=project.project_id %}" class="btn btn-normal mb-2 p-0">Back</a> {% endcomment %}
<div class="d-flex justify-content-between mb-3">
    <h3>{{ project.name }} Details</h3>
</div>
<ul class="list-group">
    {{ project.name }}
    <li class="list-group-item">Project ID : {{ project.id }}</li>
    <li class="list-group-item">Project Name : {{ project.project_name }}</li>
    <li class="list-group-item">Start Date : {{ project.project_start_date }}</li>
    <li class="list-group-item">End Date : {{ project.project_end_date }}</li>
    <li class="list-group-item">Staus : {{ project.project_status }}</li>
    <li class="list-group-item">Description : {{ project.project_description }}</li>
    <li class="list-group-item">
        <a href="{% url 'office:updateProject' project_id=project.id %}" class="btn btn-primary">Update</a>
        <a href="{% url 'office:deleteProject' project_id=project.id %}" class="btn btn-danger">Delete</a>
    </li>
</ul>

{% endblock  %}

src/templates/office/updateProject.html
{% extends 'office/base.html' %}
{% block main_block %}

{% comment %} <a href="{% url 'office:employeeDetails' %}" class="btn btn-normal mb-2 p-0">Back</a> {% endcomment %}
<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ title }}</h3>
</div>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock  %}