src/auth_app/urls.py
from django.urls import path
from auth_app import views

app_name = 'auth_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

src/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('office/', include('office.urls')),
    path('auth/', include('auth_app.urls')),
    path('cbv/', include('cbv_app.urls')),
]

src/auth_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

src/auth_app/forms.py
from django.contrib.auth.models import User
from django import forms
from auth_app.models import UserInfo


# Create your models here.
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('portfolio_site', 'profile_pic')
        widgets = {
            'portfolio_site': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control'}),
        }

src/auth_app/views.py
from django.shortcuts import render
from auth_app import forms

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    homeDict = {'title': 'Home Page'}
    return render(request, 'auth_app/index.html', context=homeDict)


# For registration
def register(request):
    registered = False
    if request.method == 'POST':
        userForm = forms.UserForm(data=request.POST)
        userInfoForm = forms.UserInfoForm(data=request.POST)

        if userForm.is_valid() and userInfoForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()

            userInfo = userInfoForm.save(commit=False)
            userInfo.user = user
            if 'profile_pic' in request.FILES:
                userInfo.profile_pic = request.FILES['profile_pic']
            userInfo.save()
            registered = True
    else:
        userForm = forms.UserForm()
        userInfoForm = forms.UserInfoForm()
    registerDict = {'title': 'Register Page', 'userForm': userForm, 'userInfoForm': userInfoForm, 'registered': registered}
    return render(request, 'auth_app/register.html', context=registerDict)


# For login
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('auth_app:index'))
            else:
                return HttpResponse('Account not active')
        else:
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request, 'auth_app/login.html')


# For logout
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('auth_app:index'))

src/templates/auth_app/index.html
{% extends 'auth_app/base.html' %}
{% load static %}
{% block main_block %}

<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ title }}</h3>
    {% if user.is_authenticated %}
        <a href="{% url 'auth_app:logout' %}" class="btn btn-danger">Logout</a>
    {% else %}
        <a href="{% url 'auth_app:register' %}" class="btn btn-primary">Register</a>
        <a href="{% url 'auth_app:login' %}" class="btn btn-primary">Login</a>
    {% endif %}
</div>

{% endblock %}

src/templates/auth_app/login.html
{% extends 'auth_app/base.html' %}
{% load static %}
{% block main_block %}

<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">Login</h3>
    <a href="{% url 'auth_app:index' %}" class="btn btn-primary">Back</a>
</div>

{% if registered %}
    <div class="alert alert-success" role="alert">
        You have successfully registered!
    </div>
{% else %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
        </div>
        <div class="form-group mt-2">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <input type="submit" name="submit" value="Login" class="btn btn-primary mt-3">
    </form>
{% endif %}

{% endblock %}

src/templates/auth_app/register.html
{% extends 'auth_app/base.html' %}
{% load static %}
{% block main_block %}

<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ title }}</h3>
    <a href="{% url 'auth_app:index' %}" class="btn btn-primary">Back</a>
</div>

{% if registered %}
    <div class="alert alert-success" role="alert">
        You have successfully registered!
    </div>
{% else %}
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ userForm.as_p }}
        {{ userInfoForm.as_p }}
        <input type="submit" name="submit" value="Register">
    </form>
{% endif %}

{% endblock %}