src/cbv_app/urls.py
from django.urls import path
from cbv_app import views

app_name = 'cbv_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('student_detail/<pk>/', views.StudentDetailView.as_view(), name='student_detail'),
    path('student_create/', views.StudentCreateView.as_view(), name='student_create'),
    path('student_update/<pk>/', views.StudentUpdateView.as_view(), name='student_update'),
    path('student_delete/<pk>/', views.StudentDeleteView.as_view(), name='student_delete'),
    path('subject_detail/<pk>/', views.SubjectDetailView.as_view(), name='subject_detail'),
]

src/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('office/', include('office.urls')),
    path('auth/', include('auth_app.urls')),
    path('cbv/', include('cbv_app.urls')),
]

src/cbv_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=20)
    batch = models.CharField(max_length=50)
    roll = models.IntegerField()

    def __str__(self):
        return self.name + " - " + str(self.roll) + " - " + self.batch
    def get_absolute_url(self):
        return reverse("cbv_app:student_detail", kwargs={"pk": self.pk})
    


class Subject(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='subjects')
    subject_name = models.CharField(max_length=50)
    subject_code = models.CharField(max_length=50)
    subject_credit = models.IntegerField()

    def __str__(self):
        return self.subject_name + " - " + self.subject_code + " - " + str(self.subject_credit)

src/cbv_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from cbv_app.models import Student, Subject
from django.urls import reverse_lazy

# Create your views here.
# For Student List View
class IndexView(ListView):
    template_name = 'cbv_app/index.html'
    model = Student
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = Student.objects.all()
        return context



# For Student Detail View
class StudentDetailView(DetailView):
    template_name = 'cbv_app/studentDetail.html'
    model = Student
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = Student.objects.all()
        return context



# For Student Create View
class StudentCreateView(CreateView):
    template_name = 'cbv_app/studentCreate.html'
    model = Student
    fields = ['name', 'email', 'phone', 'batch', 'roll']



# For Student Update View
class StudentUpdateView(UpdateView):
    template_name = 'cbv_app/studentUpdate.html'
    model = Student
    fields = ['name', 'email', 'phone', 'batch', 'roll']



# For Student Delete View
class StudentDeleteView(DeleteView):
    template_name = 'cbv_app/studentDelete.html'
    model = Student
    success_url = reverse_lazy('cbv_app:index')
    


# For Subject Detail View
class SubjectDetailView(DetailView):
    template_name = 'cbv_app/subjectDetail.html'
    model = Subject
    context_object_name = 'subject'

src/cbv_app/templates/cbv_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container py-3">
        {% block main_block %}
        
        {% endblock  %}
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

src/cbv_app/templates/cbv_app/index.html
{% extends 'cbv_app/base.html' %}
{% load static %}
{% block main_block %}
    <div class="d-flex justify-content-between mb-3">
        <h3 class="m-0">Home Page</h3>
        <a href="{% url 'cbv_app:student_create' %}" class="btn btn-primary">Add Student</a>
    </div>
    <ul>
        {% for student in students %}
            <li><a href="{% url 'cbv_app:student_detail' pk=student.pk %}">{{ student.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

src/cbv_app/templates/cbv_app/studentCreate.html
{% extends 'cbv_app/base.html' %}
{% block main_block %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock  %}

src/cbv_app/templates/cbv_app/studentDelete.html
{% extends 'cbv_app/base.html' %}
{% block main_block %}
<h3>Delete {{ student.name }}</h3>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'cbv_app:student_detail' pk=student.pk %}" class="btn btn-primary">Cancel</a>
</form>

{% endblock  %}

src/cbv_app/templates/cbv_app/studentDetail.html
{% extends 'cbv_app/base.html' %}
{% block main_block %}
<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ student.name }} Details</h3>
    <a href="{% url 'cbv_app:student_update' pk=student.pk %}" class="btn btn-warning">Edit Student</a>
    <a href="{% url 'cbv_app:student_delete' pk=student.pk %}" class="btn btn-danger">Delete Student</a>
</div>
<p>Email: {{ student.email }}</p>
<p>Phone: {{ student.phone }}</p>
<p>Batch: {{ student.batch }}</p>
<p>Roll: {{ student.roll }}</p>

<hr>

<a href="" class="btn btn-primary mb-3">Add Subject</a>
<ul>
    {% for subject in student.subjects.all %}
        <li><a href="{% url 'cbv_app:subject_detail' pk=subject.id %}">{{ subject }}</a></li>
    {% endfor %}
</ul>

{% endblock  %}

src/cbv_app/templates/cbv_app/studentUpdate.html
{% extends 'cbv_app/base.html' %}
{% block main_block %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock  %}

src/cbv_app/templates/cbv_app/subjectDetail.html
{% extends 'cbv_app/base.html' %}
{% block main_block %}
<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0">{{ subject.subject_name }} Details</h3>
    <a href="" class="btn btn-warning">Edit Subject</a>
</div>
<p>Subject Code: {{ subject.subject_code }}</p>
<p>Subject Credit: {{ subject.subject_credit }}</p>

{% endblock  %}